# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ""
author: Aviary team at NASA
logo: aviary.png
copyright: '2023'

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 240
  # execute_notebooks: auto

exclude_patterns: ["*/reports/*"]

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/openmdao/Aviary  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon : "aviary_logo.png"
  
launch_buttons:
  colab_url: "https://colab.research.google.com"

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.napoleon'
